// TODO: add ability to load a config from $HOME/.config/quoty/quotes.toml
pub const QUOTES: &[(&str, &str)] = &[
    ("Anon (16th century)", "Fuck You!"),
    ("Anon", "Compile, wait for 20 minutes, notice a new commit, compile again."),
    ("Anon", "Feel free to react if you're impressed."),
    ("Anon", "I hate it when you guys don't talk."),
    ("Anon", "In a perfect world, this would work."),
    ("Anon", "It's not easy, but it'll be easy."),
    ("Anon", "Just give it to me."),
    ("Anon", "Pay will be in on monday."),
    ("Anon", "Programmer: A machine that turns coffee into code."),
    ("Anon", "This text is random."),
    ("Anon", "Trust me bro."),
    ("Anon", "When I wrote this code, only God and I understood what I did. Now only God knows."),

    ("Alan Cooper", "If we want users to like our software, we should design it to behave like a likable person."),
    ("Alan Turing", "Sometimes it is the people no one imagines anything of, who do the things that no one can imagine."),
    ("Bill Gates", "I choose a lazy person to do a hard job. Because a lazy person will find an easy way to do it."),
    ("Brian Kernighan", "Programming is learned by writing programs."),
    ("Donald Knuth", "Premature optimization is the root of all evil."),
    ("Edsger Dijkstra", "The question of whether machines can think is about as relevant as the question of whether submarines can swim."),
    ("Ellen Ullman", "Programmers seem to be changing the world. It would be a relief, for them and for all of us, if they knew something about it."),
    ("Elon Musk", "I taught myself how to program computers when I was a kid, bought my first computer when I was 10, and sold my first commercial program when I was 12."),
    ("Fred Brooks", "The mythical man-month is a dangerous myth, as is the assumption that adding manpower to a late software project makes it later."),
    ("John Romero", "You might not think that programmers are artists, but programming is an extremely creative profession. It's logic-based creativity."),
    ("Kent Beck", "I'm not a great programmer; I'm just a good programmer with great habits."),
    ("Linus Torvalds", "Given enough eyeballs, all bugs are shallow."),
    ("Linus Torvalds", "I'm not a visionary. I'm an engineer."),
    ("Linus Torvalds", "Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program."),
    ("Linus Torvalds", "Software is like sex: it's better when it's free."),
    ("Linus Torvalds", "Talk is cheap. Show me the code."),
    ("Linus Torvalds", "The Linux kernel is a masterpiece of open source collaboration and a testament to the power of community-driven development."),
    ("Olawale Daniel", "Web development is difficult, only then it is fun to do. You just have to set your standards. If it were to be easy, would anyone do it?"),
    ("Samuel Redwine", "Software and cathedrals are much the same, first we build them, then we pray."),
    ("Steve Jobs", "Everybody should learn to program a computer because it teaches you how to think."),
    ("Steve Jobs", "Innovation distinguishes between a leader and a follower."),
    ("Vaxry", "'why no work', bro I haven't hacked your pc to get live feeds yet"),
    ("Vaxry", "Hello everyone this is YOUR daily dose of 'read the wiki'"),
    ("Vaxry", "I commit too often, people can't catch up lmao"),
    ("Yegor Bugayenk", "Quality is a product of a conflict between programmers and testers."),
];
